"""
ASCED Field of Education facet values.
Extracted to a separate file to keep facets.py manageable.
"""

ASCED_FIELD_OF_EDUCATION_FACET = {
    "facet_id": "ASCED",
    "facet_name": "ASCED Field of Education",
    "description": "Australian Standard Classification of Education (ASCED) - Field of Education classification at the narrow field (4-digit) level",
    "standard": "Australian Standard Classification of Education (ASCED) 2001",
    "reference": "https://www.abs.gov.au/statistics/classifications/australian-standard-classification-education-asced/latest-release",
    "multi_value": True,
    "values": {
        "0101": {"code": "0101", "name": "Mathematical Sciences", "description": "Mathematical Sciences disciplines.", "keywords": ["Mathematics", "Statistics"], "training_packages": []},
        "0103": {"code": "0103", "name": "Physics and Astronomy", "description": "Physics and Astronomy disciplines.", "keywords": ["Astronomy", "Physics"], "training_packages": []},
        "0105": {"code": "0105", "name": "Chemical Sciences", "description": "Chemical Sciences disciplines.", "keywords": ["Inorganic Chemistry", "Organic Chemistry"], "training_packages": []},
        "0107": {"code": "0107", "name": "Earth Sciences", "description": "Earth Sciences disciplines.", "keywords": ["Atmospheric Sciences", "Geology", "Geophysics", "Hydrology", "Oceanography", "Soil Science"], "training_packages": []},
        "0109": {"code": "0109", "name": "Biological Sciences", "description": "Biological Sciences disciplines.", "keywords": ["Biochemistry", "Botany", "Ecology", "Genetics", "Microbiology", "Zoology"], "training_packages": []},
        "0199": {"code": "0199", "name": "Other Natural and Physical Sciences", "description": "Other Natural and Physical Sciences.", "keywords": ["Food Science", "Forensic Science", "Laboratory Technology", "Pharmacology"], "training_packages": []},
        "0201": {"code": "0201", "name": "Computer Science", "description": "Computer Science disciplines.", "keywords": ["Algorithms", "Artificial Intelligence", "Programming", "Networks", "Operating Systems"], "training_packages": []},
        "0203": {"code": "0203", "name": "Information Systems", "description": "Information Systems disciplines.", "keywords": ["Database Management", "Systems Analysis", "Decision Support Systems"], "training_packages": []},
        "0299": {"code": "0299", "name": "Other Information Technology", "description": "Other Information Technology.", "keywords": ["Security Science"], "training_packages": []},
        "0301": {"code": "0301", "name": "Manufacturing Engineering and Technology", "description": "Manufacturing Engineering and Technology.", "keywords": ["Cabinet Making", "Garment Making", "Printing", "Textile Making"], "training_packages": []},
        "0303": {"code": "0303", "name": "Process and Resources Engineering", "description": "Process and Resources Engineering.", "keywords": ["Chemical Engineering", "Food Processing", "Materials Engineering", "Mining Engineering"], "training_packages": []},
        "0305": {"code": "0305", "name": "Automotive Engineering and Technology", "description": "Automotive Engineering and Technology.", "keywords": ["Automotive Engineering", "Vehicle Mechanics", "Panel Beating"], "training_packages": []},
        "0307": {"code": "0307", "name": "Mechanical and Industrial Engineering and Technology", "description": "Mechanical and Industrial Engineering.", "keywords": ["Welding", "Industrial Engineering", "Mechanical Engineering", "Toolmaking"], "training_packages": []},
        "0309": {"code": "0309", "name": "Civil Engineering", "description": "Civil Engineering disciplines.", "keywords": ["Building Services", "Construction Engineering", "Structural Engineering", "Transport Engineering"], "training_packages": []},
        "0311": {"code": "0311", "name": "Geomatic Engineering", "description": "Geomatic Engineering.", "keywords": ["Mapping Science", "Surveying"], "training_packages": []},
        "0313": {"code": "0313", "name": "Electrical and Electronic Engineering and Technology", "description": "Electrical and Electronic Engineering.", "keywords": ["Communications", "Computer Engineering", "Electrical Engineering", "Electronic Engineering"], "training_packages": []},
        "0315": {"code": "0315", "name": "Aerospace Engineering and Technology", "description": "Aerospace Engineering and Technology.", "keywords": ["Aerospace Engineering", "Air Traffic Control", "Aircraft Maintenance"], "training_packages": []},
        "0317": {"code": "0317", "name": "Maritime Engineering and Technology", "description": "Maritime Engineering and Technology.", "keywords": ["Marine Construction", "Marine Craft Operation", "Maritime Engineering"], "training_packages": []},
        "0399": {"code": "0399", "name": "Other Engineering and Related Technologies", "description": "Other Engineering and Related Technologies.", "keywords": ["Biomedical Engineering", "Environmental Engineering", "Fire Technology", "Rail Operations"], "training_packages": []},
        "0401": {"code": "0401", "name": "Architecture and Urban Environment", "description": "Architecture and Urban Environment.", "keywords": ["Architecture", "Interior Design", "Landscape Architecture", "Urban Design"], "training_packages": []},
        "0403": {"code": "0403", "name": "Building", "description": "Building disciplines.", "keywords": ["Bricklaying", "Carpentry", "Plumbing", "Painting", "Plastering", "Scaffolding"], "training_packages": []},
        "0501": {"code": "0501", "name": "Agriculture", "description": "Agriculture disciplines.", "keywords": ["Agricultural Science", "Animal Husbandry", "Wool Science"], "training_packages": []},
        "0503": {"code": "0503", "name": "Horticulture and Viticulture", "description": "Horticulture and Viticulture.", "keywords": ["Horticulture", "Viticulture"], "training_packages": []},
        "0505": {"code": "0505", "name": "Forestry Studies", "description": "Forestry Studies.", "keywords": ["Forestry Studies"], "training_packages": []},
        "0507": {"code": "0507", "name": "Fisheries Studies", "description": "Fisheries Studies.", "keywords": ["Aquaculture"], "training_packages": []},
        "0509": {"code": "0509", "name": "Environmental Studies", "description": "Environmental Studies.", "keywords": ["Land, Parks and Wildlife Management"], "training_packages": []},
        "0599": {"code": "0599", "name": "Other Agriculture, Environmental and Related Studies", "description": "Other Agriculture and Environmental Studies.", "keywords": ["Pest and Weed Control"], "training_packages": []},
        "0601": {"code": "0601", "name": "Medical Studies", "description": "Medical Studies.", "keywords": ["General Medicine", "Surgery", "Pathology", "Psychiatry", "Radiology"], "training_packages": []},
        "0603": {"code": "0603", "name": "Nursing", "description": "Nursing disciplines.", "keywords": ["Aged Care Nursing", "Critical Care Nursing", "Mental Health Nursing", "Midwifery"], "training_packages": []},
        "0605": {"code": "0605", "name": "Pharmacy", "description": "Pharmacy.", "keywords": ["Pharmacy"], "training_packages": []},
        "0607": {"code": "0607", "name": "Dental Studies", "description": "Dental Studies.", "keywords": ["Dental Assisting", "Dental Technology", "Dentistry"], "training_packages": []},
        "0609": {"code": "0609", "name": "Optical Science", "description": "Optical Science.", "keywords": ["Optical Technology", "Optometry"], "training_packages": []},
        "0611": {"code": "0611", "name": "Veterinary Studies", "description": "Veterinary Studies.", "keywords": ["Veterinary Assisting", "Veterinary Science"], "training_packages": []},
        "0613": {"code": "0613", "name": "Public Health", "description": "Public Health.", "keywords": ["Community Health", "Environmental Health", "Epidemiology", "Occupational Health and Safety"], "training_packages": []},
        "0615": {"code": "0615", "name": "Radiography", "description": "Radiography.", "keywords": ["Radiography"], "training_packages": []},
        "0617": {"code": "0617", "name": "Rehabilitation Therapies", "description": "Rehabilitation Therapies.", "keywords": ["Audiology", "Massage Therapy", "Occupational Therapy", "Physiotherapy", "Speech Pathology"], "training_packages": []},
        "0619": {"code": "0619", "name": "Complementary Therapies", "description": "Complementary Therapies.", "keywords": ["Acupuncture", "Naturopathy", "Traditional Chinese Medicine"], "training_packages": []},
        "0699": {"code": "0699", "name": "Other Health", "description": "Other Health.", "keywords": ["First Aid", "Human Movement", "Nutrition and Dietetics", "Paramedical Studies"], "training_packages": []},
        "0701": {"code": "0701", "name": "Teacher Education", "description": "Teacher Education.", "keywords": ["Teacher Education: Early Childhood", "Teacher Education: Primary", "Teacher Education: Secondary"], "training_packages": []},
        "0703": {"code": "0703", "name": "Curriculum and Education Studies", "description": "Curriculum and Education Studies.", "keywords": ["Curriculum Studies", "Education Studies"], "training_packages": []},
        "0799": {"code": "0799", "name": "Other Education", "description": "Other Education.", "keywords": [], "training_packages": []},
        "0801": {"code": "0801", "name": "Accounting", "description": "Accounting.", "keywords": ["Accounting"], "training_packages": []},
        "0803": {"code": "0803", "name": "Business and Management", "description": "Business and Management.", "keywords": ["Business Management", "Human Resource Management", "Project Management", "Quality Management"], "training_packages": []},
        "0805": {"code": "0805", "name": "Sales and Marketing", "description": "Sales and Marketing.", "keywords": ["Advertising", "Marketing", "Public Relations", "Sales"], "training_packages": []},
        "0807": {"code": "0807", "name": "Tourism", "description": "Tourism.", "keywords": ["Tourism"], "training_packages": []},
        "0809": {"code": "0809", "name": "Office Studies", "description": "Office Studies.", "keywords": ["Keyboard Skills", "Secretarial Studies"], "training_packages": []},
        "0811": {"code": "0811", "name": "Banking, Finance and Related Fields", "description": "Banking and Finance.", "keywords": ["Banking and Finance", "Insurance", "Investment"], "training_packages": []},
        "0899": {"code": "0899", "name": "Other Management and Commerce", "description": "Other Management and Commerce.", "keywords": ["Purchasing", "Warehousing", "Valuation"], "training_packages": []},
        "0901": {"code": "0901", "name": "Political Science and Policy Studies", "description": "Political Science and Policy Studies.", "keywords": ["Policy Studies", "Political Science"], "training_packages": []},
        "0903": {"code": "0903", "name": "Studies in Human Society", "description": "Studies in Human Society.", "keywords": ["Anthropology", "History", "Sociology"], "training_packages": []},
        "0905": {"code": "0905", "name": "Human Welfare Studies and Services", "description": "Human Welfare Studies.", "keywords": ["Care for the Aged", "Children's Services", "Counselling", "Social Work", "Youth Work"], "training_packages": []},
        "0907": {"code": "0907", "name": "Behavioural Science", "description": "Behavioural Science.", "keywords": ["Psychology"], "training_packages": []},
        "0909": {"code": "0909", "name": "Law", "description": "Law.", "keywords": ["Business Law", "Criminal Law", "Family Law", "Legal Practice"], "training_packages": []},
        "0911": {"code": "0911", "name": "Justice and Law Enforcement", "description": "Justice and Law Enforcement.", "keywords": ["Justice Administration", "Legal Studies", "Police Studies"], "training_packages": []},
        "0913": {"code": "0913", "name": "Librarianship, Information Management and Curatorial Studies", "description": "Librarianship and Information Management.", "keywords": ["Curatorial Studies", "Librarianship"], "training_packages": []},
        "0915": {"code": "0915", "name": "Language and Literature", "description": "Language and Literature.", "keywords": ["English Language", "Linguistics", "Literature", "Translating"], "training_packages": []},
        "0917": {"code": "0917", "name": "Philosophy and Religious Studies", "description": "Philosophy and Religious Studies.", "keywords": ["Philosophy", "Religious Studies"], "training_packages": []},
        "0919": {"code": "0919", "name": "Economics and Econometrics", "description": "Economics and Econometrics.", "keywords": ["Econometrics", "Economics"], "training_packages": []},
        "0921": {"code": "0921", "name": "Sport and Recreation", "description": "Sport and Recreation.", "keywords": ["Sport and Recreation Activities", "Sports Coaching"], "training_packages": []},
        "0999": {"code": "0999", "name": "Other Society and Culture", "description": "Other Society and Culture.", "keywords": ["Criminology", "Security Services"], "training_packages": []},
        "1001": {"code": "1001", "name": "Performing Arts", "description": "Performing Arts.", "keywords": ["Dance", "Drama", "Music"], "training_packages": []},
        "1003": {"code": "1003", "name": "Visual Arts and Crafts", "description": "Visual Arts and Crafts.", "keywords": ["Fine Arts", "Floristry", "Jewellery Making", "Photography"], "training_packages": []},
        "1005": {"code": "1005", "name": "Graphic and Design Studies", "description": "Graphic and Design Studies.", "keywords": ["Fashion Design", "Graphic Arts", "Textile Design"], "training_packages": []},
        "1007": {"code": "1007", "name": "Communication and Media Studies", "description": "Communication and Media Studies.", "keywords": ["Journalism", "Verbal Communication", "Written Communication"], "training_packages": []},
        "1099": {"code": "1099", "name": "Other Creative Arts", "description": "Other Creative Arts.", "keywords": [], "training_packages": []},
        "1101": {"code": "1101", "name": "Food and Hospitality", "description": "Food and Hospitality.", "keywords": ["Baking", "Butchery", "Cookery", "Food Hygiene", "Hospitality"], "training_packages": []},
        "1103": {"code": "1103", "name": "Personal Services", "description": "Personal Services.", "keywords": ["Beauty Therapy", "Hairdressing"], "training_packages": []},
        "1201": {"code": "1201", "name": "General Education Programmes", "description": "General Education Programmes.", "keywords": ["Literacy and Numeracy Programmes"], "training_packages": []},
        "1203": {"code": "1203", "name": "Social Skills Programmes", "description": "Social Skills Programmes.", "keywords": ["Social and Interpersonal Skills"], "training_packages": []},
        "1205": {"code": "1205", "name": "Employment Skills Programmes", "description": "Employment Skills Programmes.", "keywords": ["Career Development", "Work Practices"], "training_packages": []},
        "1299": {"code": "1299", "name": "Other Mixed Field Programmes", "description": "Other Mixed Field Programmes.", "keywords": [], "training_packages": []},
    }
}
